version: '3'
services:
  connector-ioctweet:
    image: opencti/connector-ioctweet:rolling
    environment:
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=ChangeMe
      - CONNECTOR_ID=ChangeMe
      - CONNECTOR_TYPE=EXTERNAL_IMPORT
      - CONNECTOR_NAME=IOCTweet
      - CONNECTOR_SCOPE=Url,Domain,X-OpenCTI-Hostname,IPv4-Addr
      - CONNECTOR_CONFIDENCE_LEVEL=100 # From 0 (Unknown) to 100 (Fully trusted)
      - CONNECTOR_LOG_LEVEL=info
      - IOCTweet_INTERVAL=2
      - IOCTweet_Consumer_Key=ChangeMe
      - IOCTweet_Consumer_Secret=ChangeMe
      - IOCTweet_Acess_Token=ChangeMe
      - IOCTweet_Acess_Token_Secret=ChangeMe
    restart: always